global using BulkyWeb.Controllers;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Bulky.DataAccess.Data;
global using Bulky.Models;
global using Bulky.DataAccess.Repository.IRepository;
global using Bulky.DataAccess.Repository;
global using Bulky.Utility;